FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y postgresql-client

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

RUN echo "Listing /app contents:" && ls -la /app && \
    echo "Showing run_scripts.sh content:" && cat /app/run_scripts.sh || echo "File not found"

RUN ls -la /app

RUN chmod +x /app/run_scripts.sh

ENTRYPOINT ["/app/run_scripts.sh"]