version: '3.9'

services:
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST : ${POSTGRES_HOST}
      POSTGRES_PORT : ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  db_data: