version: '3.9'

services:
  streamlit:
    build: .
    depends_on:
      - app
    ports:
      - "5432:5432"
    volumes:
      - .:/app
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST : ${POSTGRES_HOST}
      POSTGRES_PORT : ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST : ${POSTGRES_HOST}
      POSTGRES_PORT : ${POSTGRES_PORT}

volumes:
  db_data: