FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

RUN chmod +x run_scripts.sh

ENTRYPOINT ["./run_scripts.sh"]

#CMD ["./run_scripts.sh"]
#CMD ["streamlit", "run", "app.py"]